# Generated by Django 5.1.4 on 2024-12-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order'),
        ),
    ]
